{
    'name': 'Maknoon Data and security',
    'description': "Data and Security for all modules in Maknoon",
    'version': '0.0.1',
    "depends": ["mail"],

	"data": [
	# "data_mk_master_models/mk_master_data.xml",
	# "data_mk_master_models/sms_template_data.xml",
	"data_mk_student_register/general_sending_data.xml",
	# "data_mk_student_register/mk_master_data.xml",
	# #"data_mk_student_register/mk.student.register.csv",
	# "data_mk_student_managment/report_purpose_data.xml",
	# "data_mk_tests/errors_data.xml",
	# "data_general_sending/gateway_configuration.xml",
	# "data_general_sending/gateway_parameters.xml",
	"data_general_sending/general_sending_data.xml",
	# #"data_odoo_web_login/ir_config_parameter.xml",
 #    #'base_data/degree/hr.recruitment.degree.csv',
	# "csv_mk_master_models/mk.parts.csv",
	# "csv_mk_master_models/mk.surah.csv",
	# "csv_mk_master_models/mk.surah.verses.csv",
	# 'csv_mk_master_models/base_data/cities/res.country.state.csv',
 #    'csv_mk_master_models/base_data/area/res.country.state.csv',
 #    'csv_mk_master_models/base_data/districts/res.country.state.csv',
 #    #'csv_mk_master_models/base_data/employees/hr.employee.csv',
 #    'csv_mk_master_models/base_data/departments/hr.department.csv',
	# 'csv_mk_master_models/base_data/hr_jobs/hr.job.csv',
 #    'csv_mk_master_models/base_data/banks/res.bank.csv',
 #    'csv_mk_master_models/base_data/grades/mk.grade.csv',
 #    'csv_mk_master_models/base_data/mosques/mk.mosque.category.csv',
    
 #    'csv_mk_master_models/base_data/mosques/mk.mosque.csv',
 #    'csv_mk_master_models/base_data/study_year/mk.study.year.csv',
 #    'csv_mk_master_models/base_data/study_class/mk.study.class.csv',
 #    'csv_mk_master_models/base_data/periods/mk.periods.csv',
 #    'csv_mk_master_models/base_data/episode_type/mk.episode_type.csv',
 #    'csv_mk_master_models/base_data/days/mk.work.days.csv',
 #    #'csv_mk_master_models/base_data/episodes/mk.episode.csv',
 #    'data_programs/mk.programs.csv',
 #    'data_programs/mk.memorize.method.csv',
 #    'data_programs/mk.approaches.csv',
	"csv_mk_master_models/general_sending_data.xml",

],
	'installable':True,
	'auto_install':False,
	'application':True,
}
