# -*- coding: utf-8 -*-
from . import mk_surah
from . import mk_parts
from . import mk_approach
from . import mk_level
from . import mk_episode_type
from . import mk_epsoide_work
from . import mk_masjed
from . import mk_episode
#from . import mk_mosque
from . import mk_center
from . import mk_study_year
from . import mk_study_class
from . import mk_periods
from . import mk_hr_department
from . import mk_leave
from . import mk_formal_leave
from . import mk_urgent_leave
from . import mk_area
from . import mk_city
from . import mk_district
from . import mk_job
from . import mk_country
from . import mk_grade
#from . import mk_campus
from . import mk_contral_condition
from . import mk_type_contral
from . import mk_location
from . import sms_template
from . import mk_week_days
from . import mk_memorize_method
from . import mk_subject_page
from . import mk_specializations
from . import mk_age_category
from . import mk_employee
from . import mk_test_error
from . import public_job
from . import building_type
#from . import country
from . import mk_epoisode_master
